# Generated by Django 6.0.6 on 2026-08-19 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Subjects', '0002_subjects_sub_nature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('topic_id', models.CharField(primary_key=True, serialize=False)),
                ('topic_name', models.CharField(unique=True)),
                ('topic_nature', models.CharField()),
                ('date_studied', models.DateField()),
                ('difficulty', models.CharField()),
                ('self_study', models.CharField()),
                ('overview', models.CharField()),
                ('sub_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Subjects.subjects')),
            ],
        ),
    ]
