# Generated by Django 6.0.6 on 2026-08-20 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Topics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='self_study',
            field=models.CharField(null=True),
        ),
    ]
