# Generated by Django 6.0.6 on 2026-08-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Topics', '0002_alter_topics_self_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='topic_name',
            field=models.CharField(),
        ),
    ]
