# Generated by Django 6.0.6 on 2026-08-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('sub_id', models.CharField(primary_key=True, serialize=False)),
                ('sub_code', models.CharField()),
                ('sub_name', models.CharField()),
                ('sub_type', models.CharField()),
                ('credit', models.IntegerField()),
            ],
        ),
    ]
