# Generated by Django 6.0.6 on 2026-08-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='sub_nature',
            field=models.CharField(default='p and t'),
            preserve_default=False,
        ),
    ]
