# Generated by Django 6.0.6 on 2026-08-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0002_subjects_sub_nature'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='prog',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
