# Generated by Django 6.0.6 on 2026-08-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0003_subjects_prog'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='desc',
            field=models.CharField(default='programming lanuage'),
            preserve_default=False,
        ),
    ]
